// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: jsonrpc.proto

package protogen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// JSONRPCMessage represents a JSON-RPC 2.0 message
type JSONRPCMessage struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Jsonrpc string                 `protobuf:"bytes,1,opt,name=jsonrpc,proto3" json:"jsonrpc,omitempty"`
	// ID can be either string or number
	//
	// Types that are valid to be assigned to Id:
	//
	//	*JSONRPCMessage_IdString
	//	*JSONRPCMessage_IdNumber
	Id isJSONRPCMessage_Id `protobuf_oneof:"id"`
	// For requests and notifications
	Method string           `protobuf:"bytes,4,opt,name=method,proto3" json:"method,omitempty"`
	Params *structpb.Struct `protobuf:"bytes,5,opt,name=params,proto3" json:"params,omitempty"`
	// For responses
	Result *structpb.Struct `protobuf:"bytes,6,opt,name=result,proto3" json:"result,omitempty"`
	// For errors
	Error         *JSONRPCError `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JSONRPCMessage) Reset() {
	*x = JSONRPCMessage{}
	mi := &file_jsonrpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JSONRPCMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JSONRPCMessage) ProtoMessage() {}

func (x *JSONRPCMessage) ProtoReflect() protoreflect.Message {
	mi := &file_jsonrpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JSONRPCMessage.ProtoReflect.Descriptor instead.
func (*JSONRPCMessage) Descriptor() ([]byte, []int) {
	return file_jsonrpc_proto_rawDescGZIP(), []int{0}
}

func (x *JSONRPCMessage) GetJsonrpc() string {
	if x != nil {
		return x.Jsonrpc
	}
	return ""
}

func (x *JSONRPCMessage) GetId() isJSONRPCMessage_Id {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *JSONRPCMessage) GetIdString() string {
	if x != nil {
		if x, ok := x.Id.(*JSONRPCMessage_IdString); ok {
			return x.IdString
		}
	}
	return ""
}

func (x *JSONRPCMessage) GetIdNumber() int64 {
	if x != nil {
		if x, ok := x.Id.(*JSONRPCMessage_IdNumber); ok {
			return x.IdNumber
		}
	}
	return 0
}

func (x *JSONRPCMessage) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *JSONRPCMessage) GetParams() *structpb.Struct {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *JSONRPCMessage) GetResult() *structpb.Struct {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *JSONRPCMessage) GetError() *JSONRPCError {
	if x != nil {
		return x.Error
	}
	return nil
}

type isJSONRPCMessage_Id interface {
	isJSONRPCMessage_Id()
}

type JSONRPCMessage_IdString struct {
	IdString string `protobuf:"bytes,2,opt,name=id_string,json=idString,proto3,oneof"`
}

type JSONRPCMessage_IdNumber struct {
	IdNumber int64 `protobuf:"varint,3,opt,name=id_number,json=idNumber,proto3,oneof"`
}

func (*JSONRPCMessage_IdString) isJSONRPCMessage_Id() {}

func (*JSONRPCMessage_IdNumber) isJSONRPCMessage_Id() {}

// JSONRPCError represents a JSON-RPC 2.0 error
type JSONRPCError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *structpb.Struct       `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JSONRPCError) Reset() {
	*x = JSONRPCError{}
	mi := &file_jsonrpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JSONRPCError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JSONRPCError) ProtoMessage() {}

func (x *JSONRPCError) ProtoReflect() protoreflect.Message {
	mi := &file_jsonrpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JSONRPCError.ProtoReflect.Descriptor instead.
func (*JSONRPCError) Descriptor() ([]byte, []int) {
	return file_jsonrpc_proto_rawDescGZIP(), []int{1}
}

func (x *JSONRPCError) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *JSONRPCError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *JSONRPCError) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_jsonrpc_proto protoreflect.FileDescriptor

const file_jsonrpc_proto_rawDesc = "" +
	"\n" +
	"\rjsonrpc.proto\x12\ajsonrpc\x1a\x1cgoogle/protobuf/struct.proto\"\x95\x02\n" +
	"\x0eJSONRPCMessage\x12\x18\n" +
	"\ajsonrpc\x18\x01 \x01(\tR\ajsonrpc\x12\x1d\n" +
	"\tid_string\x18\x02 \x01(\tH\x00R\bidString\x12\x1d\n" +
	"\tid_number\x18\x03 \x01(\x03H\x00R\bidNumber\x12\x16\n" +
	"\x06method\x18\x04 \x01(\tR\x06method\x12/\n" +
	"\x06params\x18\x05 \x01(\v2\x17.google.protobuf.StructR\x06params\x12/\n" +
	"\x06result\x18\x06 \x01(\v2\x17.google.protobuf.StructR\x06result\x12+\n" +
	"\x05error\x18\a \x01(\v2\x15.jsonrpc.JSONRPCErrorR\x05errorB\x04\n" +
	"\x02id\"i\n" +
	"\fJSONRPCError\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12+\n" +
	"\x04data\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x04data2S\n" +
	"\x0eJSONRPCService\x12A\n" +
	"\tTransport\x12\x17.jsonrpc.JSONRPCMessage\x1a\x17.jsonrpc.JSONRPCMessage(\x010\x01B1Z/github.com/DR1N0/mcp-go/transport/grpc/protogenb\x06proto3"

var (
	file_jsonrpc_proto_rawDescOnce sync.Once
	file_jsonrpc_proto_rawDescData []byte
)

func file_jsonrpc_proto_rawDescGZIP() []byte {
	file_jsonrpc_proto_rawDescOnce.Do(func() {
		file_jsonrpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_jsonrpc_proto_rawDesc), len(file_jsonrpc_proto_rawDesc)))
	})
	return file_jsonrpc_proto_rawDescData
}

var file_jsonrpc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_jsonrpc_proto_goTypes = []any{
	(*JSONRPCMessage)(nil),  // 0: jsonrpc.JSONRPCMessage
	(*JSONRPCError)(nil),    // 1: jsonrpc.JSONRPCError
	(*structpb.Struct)(nil), // 2: google.protobuf.Struct
}
var file_jsonrpc_proto_depIdxs = []int32{
	2, // 0: jsonrpc.JSONRPCMessage.params:type_name -> google.protobuf.Struct
	2, // 1: jsonrpc.JSONRPCMessage.result:type_name -> google.protobuf.Struct
	1, // 2: jsonrpc.JSONRPCMessage.error:type_name -> jsonrpc.JSONRPCError
	2, // 3: jsonrpc.JSONRPCError.data:type_name -> google.protobuf.Struct
	0, // 4: jsonrpc.JSONRPCService.Transport:input_type -> jsonrpc.JSONRPCMessage
	0, // 5: jsonrpc.JSONRPCService.Transport:output_type -> jsonrpc.JSONRPCMessage
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_jsonrpc_proto_init() }
func file_jsonrpc_proto_init() {
	if File_jsonrpc_proto != nil {
		return
	}
	file_jsonrpc_proto_msgTypes[0].OneofWrappers = []any{
		(*JSONRPCMessage_IdString)(nil),
		(*JSONRPCMessage_IdNumber)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_jsonrpc_proto_rawDesc), len(file_jsonrpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_jsonrpc_proto_goTypes,
		DependencyIndexes: file_jsonrpc_proto_depIdxs,
		MessageInfos:      file_jsonrpc_proto_msgTypes,
	}.Build()
	File_jsonrpc_proto = out.File
	file_jsonrpc_proto_goTypes = nil
	file_jsonrpc_proto_depIdxs = nil
}
